version: '3'

services:
  web:
    build:
      context: .
      dockerfile: TRA/Dockerfile
    ports:
      - "5000:80"
   
  client:
    build:
      context: .
      dockerfile:  TRAFrontend/frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - web
  

   